[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
via_ir = true
optimizer = true
optimizer_runs = 200

[profile.ci]
fuzz_runs = 1000
verbosity = 4